networks:
  hestia-network-dev:
    name: hestia-network-dev

volumes:
  hestia-database-volume-dev:
    name: hestia-database-volume-dev

services:
  hestia-bot-dev:
    container_name: hestia-bot-dev
    healthcheck:
      test: cat /proc/1/cmdline || exit 1
      start_period: 5s
    build: 
      context: .
      dockerfile: Dockerfile.bot
    networks: 
      - hestia-network-dev
    restart: unless-stopped
    volumes:
      - /root/hestia-dev/data:/data
    working_dir: /hestia

  hestia-scraper-dev:
    container_name: hestia-scraper-dev
    healthcheck:
      test: pgrep cron || exit 1
      start_period: 5s
    build:
      context: .
      dockerfile: Dockerfile.scraper
    networks: 
      - hestia-network-dev
    restart: unless-stopped
    volumes:
      - /root/hestia-dev/data:/data
    working_dir: /scraper

  hestia-database-dev:
    container_name: hestia-database-dev
    image: postgres:latest
    networks: 
      - hestia-network-dev
    ports:
      - "5433:5432"
    restart: unless-stopped 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0000
      POSTGRES_DB: hestia
    volumes:
      - hestia-database-volume-dev:/var/lib/postgresql/data
